[ALPS08631203] gpu: fix build error due to mainline migration
[Description]
Fix build error according to Commit "4cf6336 Merge tag v6.10-rc1 into android-mainline"
1. fix error due to "use $(src) instead of $(srctree)/$(src) for source directory"
2. mali_kbase_hwcnt_gpu.c:419:33: error: parameter max_core_mask set but not used [-Werror,-Wunused-but-set-parameter]
3. remove second parameter of __assign_str()

[Test]
Build and Boot up

MTK-Commit-Id: 6f0dd6a2f97922578736876007ec7e65a2c905e5

Signed-off-by: PoShao Chen <poshao.chen@mediatek.com>
CR-Id: ALPS08631203
Feature: Kernel SI Operation
Change-Id: I2c1c2acbeb2f9a9a307f26e8ee0fa56d8a14a843