[ALPS08691756]  GPU: DDK 24.1ED Fix build error for 32 bit
[Description]
For 32 bit projects of mt6761/65, build error due to:
error: unknown type name __uint128_t
Add if/else check manually in KM code to handle it until proper fix in gpu_img_private source code.

[Test]
Build pass

MTK-Commit-Id: 1c025f6e55fdf21e03245387d5413a02c549bf5c

Change-Id: Iffda7449f4385cf30442ea7e4f42f6b89223a32f
CR-Id: ALPS08691756
Feature: IMG GPU DDK driver
Signed-off-by: akansha.shukla <akansha.shukla@mediatek.com>