[ALPS09045970] GPU: fix namespace build error
[Description]
fix namespace build error due to a38b207d4f4e of kernel-6.6

ERROR: modpost: module mali_kbase_mt6781 uses symbol close_fd from namespace VFS_internal_I_am_really_a_filesystem_and_am_NOT_a_driver, but does not import it.

[Test]
sanity/stability pass

MTK-Commit-Id: e22cad30193e48120c359cf702406d2c0eb94cd6

Signed-off-by: Clive Lin <clive.lin@mediatek.com>
CR-Id: ALPS09045970
Feature: Kernel SI Operation
Change-Id: I960b29bd65bdebdc3705e762132fbb6bac08f168