[ALPS08490829] use percpu_counter_add() instead of atomic_long_add()
Commit f1a7941243c10 (mm: convert mms rss stats into percpu_counter) changes usage of atomic_long_add

vendor/mediatek/kernel_modules/gpu/mt6897/mali_valhall/mali-r38p1/drivers/gpu/arm/midgard/mali_kbase_mem_linux.c:3394:38: error: member reference base type struct percpu_counter[4] is not a structure or union
        atomic_long_add(value, &mm->rss_stat.count[member]);
                                ~~~~~~~~~~~~^~~~~~

MTK-Commit-Id: a6658fe19aeeafa31908fa7faff2f0426c867894

Signed-off-by: Clive Lin <clive.lin@mediatek.com>
CR-Id: ALPS08490829
Feature: Kernel SI Operation
Change-Id: Ic8e2ff9ec02d67d156268ca034c83d9d0a2be10c